version: '3.8'
services:
  raffle-app:
    image: raffle-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raffle-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      # Agrega más variables según necesites
    volumes:
      - ./public:/app/public:ro